branch-defaults:
  default:
    environment: circleExpress-env
  master:
    environment: circleExpress-env
environment-defaults:
  circleExpress-env:
    branch: master
    repository: circle-express
global:
  application_name: SandboxApplication
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.3.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
